### ISSUE TITLE
Remove 'Due to (a|an)?'

### ISSUE THREAD

**Issue by grischard** [TfLlu/TravelAlertsLu#18]
Due to an emergency operation in Esch-sur-Alzette

becomes

Emergency operation in Esch-sur-Alzette

**Comment by Kaweechelchen** [comment]
actually, I try to skp the reasons completely

https://regex101.com/r/bA1vF4/1

becomes:
#RE6968 Luxembourg-Rodange
Arrival: 19:23
Delay: 15-20 minutes
